feat: Добавить функцию бронирования и комментариев
AlexGrechishnikov/java-shareit pull request #2
Opened 2022-08-04 10:58 UTC by AlexGrechishnikov

2022-08-05 07:38 UTC, kukolev requested changes

2022-08-05 07:38 UTC, kukolev commented on src/main/java/ru/practicum/shareit/booking/controller/BookingRestController.java
> +        userService.findByIdOrThrow(requestUserId);
Валидация это часть бизнес-логики. Бизнес-логика должна быть выполнена в сервисе. Логичней будет перенести этот метод в метод .create() в BookingService.

Аналогично нужно поправить в методах ниже.

2022-08-05 07:38 UTC, kukolev commented on src/main/java/ru/practicum/shareit/booking/controller/BookingRestController.java
> +        dto.setBookerId(requestUserId);
Инициализация полей должна выполняться в маппере, как вариант уже над сущностью, а не в ДТО. Вообще лучше не изменять состояние объекта в методе, если метод напрямую для этого не предназначен. Внешний код может не ожидать подобного поведения.

2022-08-05 07:38 UTC, kukolev commented on src/main/java/ru/practicum/shareit/booking/repository/BookingRepository.java
> +    List<Booking> findAllByBookerIdAndStartBeforeAndEndAfterOrderByStartDesc(
По моему такие методы очень плохо читаются в коде. Будет лучше, если названия будут короткими, а логика поиска будет реализована в `@Query`

Аналогично нужно поправить в других методах.

2022-08-05 07:38 UTC, kukolev commented on src/main/java/ru/practicum/shareit/user/controller/UsersRestController.java
> +            //Игнорируется отсутсвие удаляемого объекта для идемпотентности запроса
Рекомендую в таких случаях что-то писать в лог. Можно warning, как вариант.

2022-08-05 16:11 UTC, AlexGrechishnikov commented on src/main/java/ru/practicum/shareit/booking/controller/BookingRestController.java
> +        dto.setBookerId(requestUserId);
Досборка ДТО происходит из параметров и заголовков запроса. 
Маппер не замаппит объекты сущности, если дто будет с незаполненными полями. 
Как сделать правильнее? 
Попробовал перенести и мапинг и параметры в метод сервиса, получается громоздко и не удачно - появляются циклические зависимости.

2022-08-06 11:24 UTC, kukolev approved these changes

2022-08-06 13:46 UTC, merged