Test: добавить тесты на все приложение и небольшие доработки
AlexGrechishnikov/java-shareit pull request #3
Opened 2022-08-13 09:29 UTC by AlexGrechishnikov

2022-08-14 08:15 UTC, kukolev requested changes

2022-08-14 08:15 UTC, kukolev commented on src/test/java/ru/practicum/shareit/itemrequest/ItemRequestRestControllerTest.java
> +    void getAllMyOwnRequests() throws Exception {
Этот тест лучше разбить на несколько небольших тестов, каждый из которых проверяет что-то конкретное. Так будет проще понять что пошло не так, если один или несколько тестов упадут.

2022-08-14 08:15 UTC, kukolev commented on src/test/java/ru/practicum/shareit/user/UsersRestControllerTest.java
> +    void patchUsers() throws Exception {
Этот тест лучше разбить на несколько небольших тестов, каждый из которых проверяет что-то конкретное. Так будет проще понять что пошло не так, если один или несколько тестов упадут.

2022-08-14 08:15 UTC, kukolev commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +    public List<Item> findAllByNameOrDescriptionPatternPage(String pattern, Long requestUserId, Integer from, Integer size) {
Нарушение требований кодстайла: Очень длинная строка - превышает 120 символов в длину. Подробнее можно почитать тут: https://www.notion.so/praktikum/Code-guide-Java-d835be24c32d4265aeb4007652f40e6f#8454ceb4e0d6417d985c0418586015f1

2022-08-14 08:15 UTC, kukolev commented on src/test/java/ru/practicum/shareit/item/ItemsRestControllerTest.java
> +    void patchItems() throws Exception {
Этот тест лучше разбить на несколько небольших тестов, каждый из которых проверяет что-то конкретное. Так будет проще понять что пошло не так, если один или несколько тестов упадут.

2022-08-14 08:15 UTC, kukolev commented on src/test/java/ru/practicum/shareit/item/ItemsRestControllerTest.java
> +    void postComment() throws Exception {
Этот тест лучше разбить на несколько небольших тестов, каждый из которых проверяет что-то конкретное. Так будет проще понять что пошло не так, если один или несколько тестов упадут.

2022-08-14 08:15 UTC, kukolev commented on src/test/java/ru/practicum/shareit/itemrequest/ItemRequestModelTest.java
> +    void equalsAndHashTest() {
Для полноты проверки можно было бы еще проверить, что два равных объекта вернут два равных хэшкода.

2022-08-14 22:29 UTC, kukolev requested changes

2022-08-14 22:29 UTC, kukolev commented on src/main/java/ru/practicum/shareit/user/mapper/UserMapper.java
> +    public User toEntity(UserDto dto, Long userId) {
Для маппинга нужно делать отдельный класс - маппер. Контроллер не должен отвечать за маппинг. Нужно переделать.

2022-08-15 05:24 UTC, AlexGrechishnikov commented on src/main/java/ru/practicum/shareit/user/mapper/UserMapper.java
> +    public User toEntity(UserDto dto, Long userId) {
Написал в slack

2022-08-16 06:27 UTC, kukolev approved these changes

2022-08-16 09:00 UTC, merged